version: '4'

services:
  mysql:
    image: mysql:8.0.40-debian
    container_name: torneo_AD3
    environment:
      MYSQL_ROOT_PASSWORD: jose1986
      MYSQL_DATABASE: torneo
      MYSQL_USER: jose
      MYSQL_PASSWORD: jose1986
    volumes:
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    ports:
      - "3306:3306"
    restart: always
    

